{% set name = "sanic-security" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-security-{{ version }}.tar.gz
  sha256: 01d925f5ae423ea21393b3fe96e33c62dc20732189d913622e56c0eee77a3bce

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiofiles >=0.3.0
    - argon2-cffi >=20.1.0
    - captcha
    - pyjwt >=1.7.0
    - python >=3.6
    - sanic
    - tortoise-orm >=0.17.0

test:
  source_files:
    - sanic_security/test
  imports:
    - sanic_security
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys sanic_security/test/tests.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
