{% set name = "sanic-security" %}
{% set version = "1.16.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 61610d5e8d7e5e5a4bdc0c69316a83e51ce88d94b3eae860e8876e17aed3d536

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=58.0.0
    - wheel
  run:
    - python >={{ python_min }}
    - tortoise-orm >=0.17.0
    - pyjwt >=1.7.0
    - captcha >=0.4
    - pillow >=9.5.0
    - argon2-cffi >=20.1.0
    - sanic >=21.3.0
    # Contraints from tortoise-orm 0.19.3
    - iso8601 <2.0.0,>=1.0.2
    - secure >=1.0.1

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
