{% set name = "sanic-security" %}
{% set version = "1.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2e055131ddd6ee0550e43f620ca3d2bb6920b8706e62915e937dc4732dc4ab35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6
    - setuptools >=58.0.0
    - wheel
  run:
    - argon2-cffi >=20.1.0
    - captcha ==0.4
    - pillow ==9.5.0
    - pyjwt >=1.7.0
    - python >=3.6
    - sanic >=21.3.0
    - tortoise-orm >=0.17.0

    # Contraints from tortoise-orm 0.19.3
    - iso8601 <2.0.0,>=1.0.2

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
