{% set name = "sanic-security" %}
{% set version = "0.10.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-security-{{ version }}.tar.gz
  sha256: 338eef3c3b2803452ce238c0d765111f93f29883f969e20d8880ade75d7f6f13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiofiles
    - aiosmtplib
    - captcha
    - httpx >=0.18.2
    - pyjwt
    - python >=3.6
    - sanic ==21.3.4
    - tortoise-orm ==0.17.4

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
