{% set name = "sanic-security" %}
{% set version = "1.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 01250b855b95b15dd9866472b904bd20e53e95764b468c72d6f7f8f7dc9c5f5f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - argon2-cffi >=20.1.0
    - captcha
    - pyjwt >=1.7.0
    - python >=3.6
    - sanic >=21.3.0
    - tortoise-orm >=0.17.0

    # Contraints from tortoise-orm 0.19.3
    - iso8601 <2.0.0,>=1.0.2

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
