{% set name = "sanic-security" %}
{% set version = "1.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-security-{{ version }}.tar.gz
  sha256: 7c6eeeb6ec49d13a3a51ba3065493b97c684a60ceba5f9e0a0a301e4fb0567c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - argon2-cffi >=20.1.0
    - captcha
    - pyjwt >=1.7.0
    - python >=3.6
    - sanic
    - tortoise-orm >=0.17.0

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
