{% set name = "sanic-security" %}
{% set version = "1.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-security-{{ version }}.tar.gz
  sha256: c3fbf52b85dabcc54e5a8fa3404aa9bbf9085baf3c9ccbba1f85b27f34cce27a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - argon2-cffi >=20.1.0
    - captcha
    - pyjwt >=1.7.0
    - python >=3.6
    - sanic >=21.3.0
    - tortoise-orm >=0.17.0

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
