{% set name = "sanic-security" %}
{% set version = "0.10.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-security-{{ version }}.tar.gz
  sha256: a451e6c03bb91f25b84ae7e7442fac22842e1793030b5f6331f6ca804c2b7cdf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiofiles
    - aiosmtplib
    - captcha
    - httpx >=0.18.2
    - pyjwt
    - python >=3.6
    - sanic ==21.3.4
    - tortoise-orm ==0.17.4

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
