{% set name = "sanic-security" %}
{% set version = "1.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5fa4f600f3bc64281ed73ca84a3cbdffe79499b7512afa042d17bb5300161ab3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=58.0.0
  run:
    - python >=3.8
    - tortoise-orm >=0.17.0
    - pyjwt >=1.7.0
    - captcha >=0.4
    - pillow >=9.5.0
    - argon2-cffi >=20.1.0
    - sanic >=21.3.0
    # Contraints from tortoise-orm 0.19.3
    - iso8601 <2.0.0,>=1.0.2

test:
  imports:
    - sanic_security
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sunset-developer/sanic-security
  doc_url: http://security.sunsetdeveloper.com/
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
