schema_version: 1

context:
  name: sanic-security
  version: "1.17.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 6384f77a070605898d1f37e526da83705b68b551466018eef11720bf577dc202

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - tortoise-orm >=1.1.8
    - pyjwt >=2.13.0
    - captcha >=0.4
    - argon2-cffi >=20.1.0
    - sanic >=25.12.1
    - aiosmtplib >=5.1.2

tests:
  - python:
      imports:
        - sanic_security
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/sunset-developer/sanic-security
  documentation: http://security.sunsetdeveloper.com/

extra:
  recipe-maintainers:
    - thewchan
