schema_version: 1

context:
  name: sanic-security
  version: 1.16.11
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b44a75c3505cca258eebb0aaff9f0b709339a3feb599ef3d74f59d8e24d112c9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=58.0.0
    - wheel
  run:
    - python >=${{ python_min }}
    - tortoise-orm >=0.17.0
    - pyjwt >=1.7.0
    - captcha >=0.4
    - argon2-cffi >=20.1.0
    - sanic >=21.3.0

tests:
  - python:
      imports:
        - sanic_security
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A powerful, simple, and async security library for Sanic.
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/sunset-developer/sanic-security
  documentation: http://security.sunsetdeveloper.com/

extra:
  recipe-maintainers:
    - thewchan
